In [1]:
import numpy as np


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_dervative(x):
    return x*(1-x)

In [4]:
X=np.array([[0,0],
            [0,1],
            [1,0],
            [1,1]])
y= np.array([[0],[0],[0],[1]])

#wts and bais
weights=np.random.rand(2,1)
bias=np.random.rand(1)
print("Initial wts:",weights)
print("Initial bias:", bias)

Initial wts: [[0.53259513]
 [0.81187062]]
Initial bias: [0.94115652]


In [5]:
learning_rate=0.01
epochs=1000

In [6]:
print("Testing AND gate before training:")
for i in range(len(X)):
    input_data=X[i]
    output=sigmoid(np.dot(input_data,weights)+bias)
    print(f"INPUT:{input_data},normal_output:{output},Output:{np.round(output)}")

Testing AND gate before training:
INPUT:[0 0],normal_output:[0.71933321],Output:[1.]
INPUT:[0 1],normal_output:[0.85233421],Output:[1.]
INPUT:[1 0],normal_output:[0.81362695],Output:[1.]
INPUT:[1 1],normal_output:[0.90767926],Output:[1.]


In [7]:
for epoch in range(epochs):
    input_layer=X
    weighted_sum=np.dot(input_layer,weights)+bias
    activated_output=sigmoid(weighted_sum)
    print(activated_output)
    #error
    error=y-activated_output

    #adjust the backpropagation
    adjust=error*sigmoid_dervative(activated_output)
    weights+=np.dot(input_layer.T,adjust)*learning_rate
    bias+=np.sum(adjust)*learning_rate
    

[[0.71933321]
 [0.85233421]
 [0.81362695]
 [0.90767926]]
[[0.71858935]
 [0.85174461]
 [0.81289223]
 [0.90718929]]
[[0.71784319]
 [0.85115212]
 [0.81215417]
 [0.90669619]]
[[0.71709472]
 [0.85055672]
 [0.81141276]
 [0.90619995]]
[[0.71634394]
 [0.84995842]
 [0.81066799]
 [0.90570056]]
[[0.71559085]
 [0.84935719]
 [0.80991985]
 [0.90519799]]
[[0.71483547]
 [0.84875304]
 [0.80916834]
 [0.90469223]]
[[0.71407778]
 [0.84814595]
 [0.80841346]
 [0.90418328]]
[[0.71331779]
 [0.84753592]
 [0.80765519]
 [0.9036711 ]]
[[0.7125555 ]
 [0.84692292]
 [0.80689353]
 [0.90315568]]
[[0.71179091]
 [0.84630697]
 [0.80612848]
 [0.90263701]]
[[0.71102403]
 [0.84568804]
 [0.80536003]
 [0.90211507]]
[[0.71025485]
 [0.84506614]
 [0.80458817]
 [0.90158985]]
[[0.70948339]
 [0.84444124]
 [0.80381291]
 [0.90106133]]
[[0.70870963]
 [0.84381335]
 [0.80303423]
 [0.90052949]]
[[0.70793359]
 [0.84318246]
 [0.80225213]
 [0.89999431]]
[[0.70715527]
 [0.84254855]
 [0.80146661]
 [0.8994558 ]]
[[0.70637467]
 [0.84191162]
 [0

In [8]:
print("Final weights:",weights)
print("Final bias:",bias)


Final weights: [[0.46215611]
 [0.63504442]]
Final bias: [-1.16542318]


In [9]:
#testing the AND gate
for i in range(len(X)):
    input_data=X[i]
    output=sigmoid(np.dot(input_data,weights)+bias)
    print(f"Input:{input_data},Output:{np.round(output).astype(int)}")

Input:[0 0],Output:[0]
Input:[0 1],Output:[0]
Input:[1 0],Output:[0]
Input:[1 1],Output:[0]
